name: BetterFarmland
version: ${version}
main: de.rafael.plugins.better.farmland.BetterFarmland
api-version: 1.16
authors: [ HttpRafa ]
description: Meant to improve your experience with your farmland
